name: Trigger E2E Tests

on:
  workflow_dispatch: 
  push:
    branches: [main, master]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger tests repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TESTS_REPO_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Qoshuq/lucid_autotests/dispatches \
          -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
